Models/JokeDTO.cs
namespace XCoreAssignment.Models;

public class JokeDTO
{
    public bool Error { get; set; }
    public string Category { get; set; }
    public string Type { get; set; }
    public string Setup { get; set; }
    public string Delivery { get; set; }
    public Flags Flags { get; set; }
    public bool Safe { get; set; }
    public int Id { get; set; }
    public string Lang { get; set; }
}

public class Flags
{
    public bool Nsfw { get; set; }
    public bool Religious { get; set; }
    public bool Political { get; set; }
    public bool Racist { get; set; }
    public bool Sexist { get; set; }
    public bool Explicit { get; set; }
}

ViewModels/Utility/UtilityTemplateVM.cs
using Application.Common.Validations;
using Application.Utility;
using Domain.Entities;
using System.ComponentModel.DataAnnotations;

namespace XCoreAssignment.ViewModels.Utility;

public class UtilityTemplateVM
{
    public UtilityTemplateVM()
    {

    }

    public UtilityTemplateVM(PaymentInfo paymentInfo)
    {
        CreditorName = paymentInfo.CreditorName;
        CreditorAddressLine = paymentInfo.CreditorAddressLine;
        CreditorCity = paymentInfo.CreditorCity;
        PaymentDescription = paymentInfo.PaymentDescription;
        PurposeCode = paymentInfo.PurposeCode;
        Amount = paymentInfo.Amount;
        CurrencyCode = paymentInfo.CurrencyCode;
        CreditorAccount = paymentInfo.CreditorAccount;
        CreditorReference = paymentInfo.CreditorReference;
        CreditorReferenceModel = paymentInfo.CreditorReferenceModel;
    }

    public string? ErrorMessage { get; set; }

    [Display(Name = "Account")]
    [Required]
    public int? DebtorAccountId { get; set; }

    public List<AccountDTO> DebtorAccounts  = AccountsDummy.Accounts;


    [Display(Name = "Name")]
    [Required]
    public string DebtorName { get; } = "John Do";

    [Display(Name = "Address line")]
    [Required]
    public string DebtorAddressLine { get; } = "Joke Street 69";

    [Display(Name = "City")]
    [Required]
    public string DebtorCity { get; } = "10009 Joke City";



    [Display(Name = "Amount")]
    [Required]
    [RegularExpression(@"^\d{1,3}(,\d{3})*(\.\d+)?$", ErrorMessage = "Please enter a valid number in the format of 1,000.00")]
    public string? Amount { get; set; }



    [Display(Name = "Name")]
    [Required]
    public string? CreditorName { get; set; }

    [Display(Name = "Address line")]
    [Required]
    public string? CreditorAddressLine { get; set; }

    [Display(Name = "City")]
    [Required]
    public string? CreditorCity { get; set; }

    [Display(Name = "Payment description")]
    [Required]
    public string? PaymentDescription { get; set; }

    [Display(Name = "Purpose code")]
    [Required]
    public string? PurposeCode { get; set; }

    [Display(Name = "Currency code")]
    [Required]
    [CustomValidation(typeof(CurrencyCodeValidation), "ValidateCurrencyCode")]
    public string? CurrencyCode { get; set; }

    [Display(Name = "Account")]
    [Required]
    public string? CreditorAccount { get; set; }

    [Display(Name = "Reference")]
    [Required]
    public string? CreditorReference { get; set; }

    [Display(Name = "Reference model")]
    [Required]
    public string? CreditorReferenceModel { get; set; }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace XCoreAssignment.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }
}

Controllers/QRController.cs
using Microsoft.AspNetCore.Mvc;
using XCoreAssignment.Services;

namespace XCoreAssignment.Controllers;

public class QRController : Controller
{

    private readonly IQRControllerService _qrControllerService;

    public QRController(IQRControllerService qrControllerService)
    {
        _qrControllerService = qrControllerService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var result = _qrControllerService.IndexGet();
        return View(result.View, result.Model);
    }

    [HttpPost]
    public IActionResult Index(IFormFile FormFile)
    {
        var result = _qrControllerService.IndexPost(FormFile);
        return View(result.View, result.Model);
    }

}

Controllers/UtilityController.cs
using Application.Common.CustomAttributes;
using Microsoft.AspNetCore.Mvc;
using XCoreAssignment.Services;
using XCoreAssignment.ViewModels.Utility;

namespace XCoreAssignment.Controllers;

public class UtilityController : Controller
{
    private readonly IUtilityControllerService _utilityService;

    public UtilityController(IUtilityControllerService utilityService)
    {
        _utilityService = utilityService;
    }

    public IActionResult Template()
    {
        var viewResult = _utilityService.TemplateGet();
        return View(viewResult.View,viewResult.Model);
    }

    [HttpPost]
    [CheckModelState]
    public async Task<IActionResult> Template(UtilityTemplateVM vm)
    {
        var viewResult = await _utilityService.TemplatePostAsync(vm);
        return View(viewResult.View, viewResult.Model);
    }
}

Views/Home/Index.cshtml
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Utility payment</h1>
        <div class="d-grid gap-3">
            <a href="/Utility/Template" class="btn btn-lg btn-outline-primary rounded-pill py-3" style="font-size: 0.88rem;"><img src="~/images/paper-icon.png" alt="Paper icon" class="me-2" width="24">TEMPLATE</a>
            <a href="/QR" class="btn btn-lg btn-outline-primary rounded-pill py-3" style="font-size: 0.88rem;"><img src="~/images/qr-code-icon.png" alt="QR code icon" class="me-2" width="24">QR CODE</a>
        </div>
    </div>
</div>

Views/QR/Index.cshtml
@{
    ViewData["Title"] = "QR Code";
}


<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Select QR code</h1>
        <form method="post" enctype="multipart/form-data">
            <div class="d-flex justify-content-center flex-column">

                <input type="file" name="FormFile" hidden="" id="getFile" accept="image/png, image/jpeg">
                <div class="d-flex justify-content-center">
                    <a style="background-color:transparent;border:hidden; margin:0;padding:0;padding-left:0.5rem;display:inline;" onclick="document.getElementById('getFile').click()">
                    <div href="/QR" class="btn btn-lg btn-outline-primary rounded-pill py-3" style="font-size: 0.88rem;"><img src="~/images/qr-code-icon.png" alt="QR code icon" class="me-2" width="24">Choose image</div>
                </a>
                </div>
                <div class="d-flex justify-content-center mt-2">
                    <p id="attachment" style="font-size: 13px; margin: 0; padding: 0;"></p>
                </div>

            </div>

            <div class="d-flex mt-4">
                <div id="proceedDiv" class="d-flex w-100 d-flex justify-content-center d-none">
                    <button id="proceed" class="btn btn-primary w-50">Proceed</button>
                </div>
                
            </div>
        </form>
    </div>
</div>

<script>
    let getFileInput = document.getElementById('getFile');
    if (getFileInput) {
        getFileInput.onchange = function () {

            var attachment = document.getElementById('attachment');

            if (this.files.length >= 1) {
                let innerHTML = "";
                for (let i = 0; i < this.files.length; i++) {
                    innerHTML += "<p class=\"m-0\">" + this.files[i].name + " is chosen</p>";
                }
                attachment.innerHTML = innerHTML;
                attachment.style.fontWeight = "bold";
                $('#proceedDiv').removeClass('d-none')
            } else {
                attachment.innerHTML = "";
                attachment.style.fontWeight = "";
                $('#proceedDiv').addClass('d-none')

            }
        }
    }
</script>

Views/Shared/Exception.cshtml
@model string

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Something went wrong...</h1>
        <div class="d-grid gap-3 fs-5 text-center">
            @Model
        </div>
    </div>
</div>

Views/Shared/Joke.cshtml
@model Application.Utility.JokeDTO

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Success! Now to the joke...</h1>
        <div class="d-grid gap-3 fs-5 text-center">
            <p>Setup: @(string.IsNullOrWhiteSpace(Model.Setup) ? "/" : Model.Setup)</p>
            <p>Delivery: @(string.IsNullOrWhiteSpace(Model.Delivery) ? "/" : Model.Delivery)</p>
        </div>
    </div>
</div>

Views/Shared/Success.cshtml
@model string

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Success</h1>
        <div class="d-grid gap-3 fs-5 text-center">
            @Model
        </div>
        <br />
        <a class="btn btn-primary" href="/">Go to main screen</a>
    </div>
</div>

Views/Shared/Suprice.cshtml
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 500px;">
        <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Almost...</h1>
        <img src="~/images/cat.jpg" /> 
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XCoreAssignment</title>
    <link href="~/css/animate.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XCoreAssignment.styles.css" asp-append-version="true" />
    <style>
        html, body {
            overflow: hidden;
        }

     
    </style>
</head>
<body class="m-0">
    <div id="modal"></div>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
        
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/modal.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Utility/Template.cshtml
@model XCoreAssignment.ViewModels.Utility.UtilityTemplateVM

<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }
</style>

<form method="post" asp-action="Template" asp-controller="Utility">
    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="card p-4 shadow-lg rounded-3 animate__animated animate__fadeInUp" style="max-width: 1200px;width:1180px">
            <h1 class="fw-bold text-center mb-4" style="font-family: 'Montserrat', sans-serif; font-size: 2rem;">Send money</h1>
            <br />

            <div class="d-flex justify-content-center gap-5">
                <div class="w-100 d-grid gap-3">

                    <h4><b><center>Sender</center></b></h4>

                    <div class="form-floating">
                        <select asp-for="DebtorAccountId" class="form-select" placeholder="Account">
                            <option value="null">--- Choose ---</option>
                            @foreach (var acc in Model.DebtorAccounts)
                        {
                                <option value="@acc.Id">@acc.Account</option>
                        }
                        </select>
                        <label asp-for="DebtorAccountId"></label>
                        <span class="text-danger" asp-validation-for="DebtorAccountId"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="DebtorName" placeholder="Name">
                        <label asp-for="DebtorName"></label>
                        <span class="text-danger" asp-validation-for="DebtorName"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="DebtorAddressLine" placeholder="Address line">
                        <label asp-for="DebtorAddressLine"></label>
                        <span class="text-danger" asp-validation-for="DebtorAddressLine"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="DebtorCity" placeholder="City">
                        <label asp-for="DebtorCity"></label>
                        <span class="text-danger" asp-validation-for="DebtorCity"></span>
                    </div>




                </div>

                <div class="w-100 d-grid gap-3">
                    <h4><b><center>Amount</center></b></h4>

                    <div class="form-floating">
                        <input class="form-control" asp-for="Amount" placeholder="Amount">
                        <label asp-for="Amount"></label>
                        <span class="text-danger" asp-validation-for="Amount"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CurrencyCode" placeholder="Currency code">
                        <label asp-for="CurrencyCode"></label>
                        <span class="text-danger" asp-validation-for="CurrencyCode"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="PurposeCode" placeholder="Purpose code">
                        <label asp-for="PurposeCode"></label>
                        <span class="text-danger" asp-validation-for="PurposeCode"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="PaymentDescription" placeholder="Payment description">
                        <label asp-for="PaymentDescription"></label>
                        <span class="text-danger" asp-validation-for="PaymentDescription"></span>
                    </div>

                </div>

                <div class="w-100 d-grid gap-3">
                    <h4><b><center>Receiver</center></b></h4>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorAccount" placeholder="Account">
                        <label asp-for="CreditorAccount"></label>
                        <span class="text-danger" asp-validation-for="CreditorAccount"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorName" placeholder="Name">
                        <label asp-for="CreditorName"></label>
                        <span class="text-danger" asp-validation-for="CreditorName"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorAddressLine" placeholder="Address line">
                        <label asp-for="CreditorAddressLine"></label>
                        <span class="text-danger" asp-validation-for="CreditorAddressLine"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorCity" placeholder="City">
                        <label asp-for="CreditorCity"></label>
                        <span class="text-danger" asp-validation-for="CreditorCity"></span>
                    </div>



                </div>

                <div class="w-100 d-flex flex-column gap-3">
                    <h4><b><center>Reference</center></b></h4>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorReference" placeholder="Reference">
                        <label asp-for="CreditorReference"></label>
                        <span class="text-danger" asp-validation-for="CreditorReference"></span>
                    </div>

                    <div class="form-floating">
                        <input class="form-control" asp-for="CreditorReferenceModel" placeholder="Reference model">
                        <label asp-for="CreditorReferenceModel"></label>
                        <span class="text-danger" asp-validation-for="CreditorReferenceModel"></span>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center mt-4 gap-5">
                <div class="w-100"></div>
                <div class="w-100"></div>
                <div class="w-100"></div>
                <button id="proceed" class="btn btn-primary w-100">Proceed</button>
            </div>

        </div>
    </div>
</form>